version: 2.1
executors:
    go:
        docker:
            - image: cimg/go:1.17.3
jobs:
    job_a:
        executor: go
        steps:
            - checkout
            - run: echo Running job a
            - run: cat path_a/README.md
    job_b:
        executor: go
        steps:
            - checkout
            - run: echo running job b
            - run: cat path_b/README.md
workflows:
    job-workflow:
        jobs:
            - job_a
            - job_b
